sudo: required
services:
  - docker

before_install:
  - docker build -t totsawin/multi-client ./client
  - docker build -t totsawin/multi-nginx ./nginx
  - docker build -t totsawin/multi-server ./server
  - docker build -t totsawin/multi-worker ./worker

script:  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push totsawin/multi-client
  - docker push totsawin/multi-nginx
  - docker push totsawin/multi-server
  - docker push totsawin/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-west-1-306476627547
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY